/*
 * PRTERM - build host tool
 * embed.c - turn a static asset (css/js) into a C translation unit
 *           holding a NUL terminated byte array.
 *
 * usage: prterm_embed <input> <output> <symbol>
 *
 * Runs on the build host only, it is never part of the CGI binary.
 *
 * SPDX-License-Identifier: MIT
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void die(const char *what, const char *arg)
{
    fprintf(stderr, "prterm_embed: %s%s%s\n", what, arg ? ": " : "", arg ? arg : "");
    exit(EXIT_FAILURE);
}

static int is_ident_char(char c, int first)
{
    if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_')
        return 1;
    if (!first && c >= '0' && c <= '9')
        return 1;
    return 0;
}

int main(int argc, char **argv)
{
    if (argc != 4) {
        fprintf(stderr, "usage: prterm_embed <input> <output> <symbol>\n");
        return 2;
    }

    const char *in_path  = argv[1];
    const char *out_path = argv[2];
    const char *symbol   = argv[3];

    if (symbol[0] == '\0')
        die("empty symbol name", NULL);
    for (const char *p = symbol; *p != '\0'; p++) {
        if (!is_ident_char(*p, p == symbol))
            die("symbol is not a C identifier", symbol);
    }

    FILE *in = fopen(in_path, "rb");
    if (in == NULL)
        die("cannot open input", in_path);

    FILE *out = fopen(out_path, "wb");
    if (out == NULL) {
        fclose(in);
        die("cannot open output", out_path);
    }

    fprintf(out, "/* generated by prterm_embed from %s - do not edit */\n", in_path);
    fprintf(out, "#include \"asset.h\"\n\n");
    fprintf(out, "const unsigned char %s[] = {", symbol);

    unsigned char buf[4096];
    unsigned long total = 0;
    size_t n;
    int col = 0;

    while ((n = fread(buf, 1, sizeof buf, in)) > 0) {
        for (size_t i = 0; i < n; i++) {
            if (col == 0)
                fputs("\n    ", out);
            fprintf(out, "0x%02x,", buf[i]);
            col = (col + 1) % 12;
            total++;
        }
    }
    if (ferror(in)) {
        fclose(in);
        fclose(out);
        die("read error", in_path);
    }
    fclose(in);

    /* explicit terminator so the array is usable as a C string */
    if (col != 0)
        fputs("\n    ", out);
    fputs("0x00\n};\n", out);
    fprintf(out, "const unsigned long %s_len = %luUL;\n", symbol, total);

    if (fclose(out) != 0)
        die("write error", out_path);

    return 0;
}
